import type { Metadata } from 'next'
import { JetBrains_Mono } from 'next/font/google'
import './globals.css'
import { Providers } from './Providers'
import { Navigation } from '@/components/layout/Navigation'

const JetBrainsFont = JetBrains_Mono({
	subsets: ['cyrillic', 'latin'],
	weight: '400'
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={JetBrainsFont.className}>
				<Providers>
					<Navigation />
					<main className="min-h-screen bg-zinc-950 text-zinc-100">
						{children}
					</main>
				</Providers>
			</body>
		</html>
	)
}
